### ISSUE TITLE
malloc(): memory corruption

### ISSUE THREAD

**Issue by jmfa** [elkebir-group/SPhyR#2]
Hi,

I'm trying to run SPhyR on a couple of datasets with a few thousand SNVs but I keep getting the following error while running it:
```
$ ./kDPFC snvset.1.sphyr -a $ERR -b $ADO -k 1 -t 4 > snvset.1.sphyr.result
Number of fixed characters = 1862
Number of fixed taxa = 0
Base log likelihood = -7966.9
malloc(): memory corruption
```

Do you have any idea of what might be causing this error?
Thanks in advance,
J

**Comment by melkebir** [comment]
This should be resolved now with the latest commit (a3b0ebefa6de4d8d804c85a14fc69fe101b7c4eb)
